### ISSUE TITLE
Token Stealer!

### ISSUE THREAD

**Issue by testttbqwebg** [Shade3421/Nightmare#1]
imagine putting token stealer into every project u made
https://raw.githubusercontent.com/Rdimo/Discord-Injection/master/injection.js
https://github.com/Shade3421/Nightmare/blob/main/utils/__pycache__/teddybuilder.cpython-310.pyc

**Comment by Shade3421** [comment]
> imagine putting token stealer into every project u made
> 
> https://raw.githubusercontent.com/Rdimo/Discord-Injection/master/injection.js
> 
> https://github.com/Shade3421/Nightmare/blob/main/utils/__pycache__/teddybuilder.cpython-310.pyc

It's a builder u fucking idiot
